### ISSUE TITLE
Translation ?

### ISSUE THREAD

**Issue by ghost** [dh4/cen64-qt#3]
Hi,

Thank you for this very well done GUI.

Is this possible to submit translation (French), and if so, how to proceed? Same question for mupen64plus-qt.

**Comment by dh4** [comment]
Yes, very possible. You would use Qt Linguist to work with a TS file. 

See this for more information:
https://doc.qt.io/qt-5.5/linguist-translators.html

This page might also interest you as well:
https://doc.qt.io/qt-5.5/linguist-manager.html

I'll get this setup for you when I have some time.

**Comment by ghost** [comment]
I have began to read those pages.

Qt Linguist is now installed.

With command line : 
lupdate -pro  mupen64plus-qt.pro  -ts mupen64plus-qt.ts

I have obtained a file to translate in QT Linguist.

Correct me if I'm wrong. Then I must give you the ts file to compile.

**Comment by dh4** [comment]
Yes, that's the general idea. If you want to wait a few days though, I'm going to go through the source code and see what text I've missed marking as translatable since I was lazy at points with that while coding this.

**Comment by ghost** [comment]
Of course.  I just wanted to be sure that I could do this translation, because I am not a developer. But no need to rush (by the way, English is not my native language, so if what I say seems sometimes strange, that is normal...).

**Comment by dh4** [comment]
Your English seems fine to me.

I've added the .ts file you can work with at resources/locale/cen64-qt_fr.ts. If you want, you can fork the repository and then edit that file and submit the changes as a pull request. Let me know if you have any questions or issues. 

There could also be text left that doesn't appear within the .ts file for you to translate. If you spot some, let me know.

I've also added the ability to change the language under Settings->Configure->Other->Language. Currently changing the language to French will do nothing since nothing has been translated yet, but if you want to test out your translations, run `lrelease cen64-qt.pro` to generate the .qm file and then recompile the application.

I've also added these changes to Mupen64Plus-Qt if you want to translate that as well.

Thanks for translating this!

**Comment by ghost** [comment]
ok, I have tried and it works fine. I begin the translation, it wil take me probably several days, or 1 week if I have less time than I thought.

**Comment by ghost** [comment]
Almost done. I can't finish the translation in the next days, but there is no problem to finish what remains (5-10%) very soon.

**Comment by dh4** [comment]
Alright, thanks! No rush.

**Comment by dh4** [comment]
Did you finish the translation?

**Comment by ghost** [comment]
ok, this is not perfect. I would have probably  to make some changes later,  but I think it is good for now.

**Comment by dh4** [comment]
Awesome thanks!

I've updated the .qm file so the development version now compiles with the translation and also fixed a few minor issues with spacing in the settings dialog.

Also added one more translation I missed before: "Game Cover" under QObject if you want to translate that. "No Cart" under MainWindow is untranslated as well.

Thanks so much for doing this!

**Comment by dh4** [comment]
I've also merged as much of this translation into the Mupen64Plus-Qt translation to aid you if you want to work on that one as well.
